[package]
name = "pdfium"
version = "0.1.0"
authors = ["Maximilian Luz <m@mxnluz.io>"]
edition = "2021"

[dependencies]
libloading = "0.7.4"
nalgebra = "0.32.2"
pdfium-sys = { path = "../pdfium-sys" }
thiserror = "1.0.39"
