[package]
edition = "2021"
name = "paper"
authors = ["Maximilian Luz <m@mxnluz.io>"]
version = "0.1.0"

[dependencies]
adw = {version = "0.3.1", package = "libadwaita", features = ["v1_2"]}
gtk = {version = "0.6.2", package = "gtk4", features = ["xml_validation", "v4_8"]}
nalgebra = "0.32.2"

[build-dependencies]
glib-build-tools = "0.17.0"
